spring:
  application:
    name: product-ms

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch:
      registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    #info:
    #show-details: always
    #enabled: true
    health:
      show-details: always
